[server]
port = 8502
maxMessageSize = 500
# fileWatcherType = "none"

[browser]
serverPort = 8502

[theme]

# # The preset Streamlit theme that your custom theme inherits from.
# # One of "light" or "dark".
base = "dark"

# # Primary accent color for interactive elements.
primaryColor = "#1f77b4"

# # Background color for the main content area.
backgroundColor = "#0e1117"

# # Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#262730"

# # Color used for almost all text.
textColor = "#fafafa"

# # Font family for all text in the app, except code blocks. One of "sans serif",
# # "serif", or "monospace".
font = "sans serif"

